# Generated by Django 4.2.4 on 2023-11-08 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkingchallenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='allocated_spots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='num_spots',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_number', models.IntegerField()),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parkingchallenge.car')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingchallenge.parkinglot')),
            ],
        ),
    ]
