# Generated by Django 4.2.4 on 2023-11-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingchallenge', '0003_remove_parkinglot_allocated_spots_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglot',
            name='is_full',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='spot_size',
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='spot_size_length',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='spot_size_width',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='square_footage',
            field=models.IntegerField(default=8),
        ),
    ]
