# Generated by Django 4.2.4 on 2023-11-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingchallenge', '0004_remove_parkinglot_is_full_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='slot_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='num_spots',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='spot_size_length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='spot_size_width',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='square_footage',
            field=models.IntegerField(),
        ),
    ]
