# Generated by Django 4.2.4 on 2023-11-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingchallenge', '0005_car_slot_number_parkinglot_num_spots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='num_spots',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='spot_size_length',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='spot_size_width',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='square_footage',
            field=models.IntegerField(default=99),
        ),
    ]
