# Generated by Django 4.2.4 on 2023-11-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingchallenge', '0006_alter_parkinglot_num_spots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='num_spots',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='spot_size_width',
            field=models.IntegerField(default=12),
        ),
    ]
