# Generated by Django 4.2.4 on 2023-11-08 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingchallenge', '0008_alter_parkinglot_num_spots_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='slot_number',
            new_name='num_spots',
        ),
    ]
