# Generated by Django 4.2.4 on 2023-11-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingchallenge', '0009_rename_slot_number_car_num_spots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='spot_size_length',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='square_footage',
            field=models.IntegerField(default=2000),
        ),
    ]
