# Generated by Django 4.2.4 on 2023-11-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingchallenge', '0010_alter_parkinglot_spot_size_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='spot_size_length',
            field=models.IntegerField(default='8', max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='spot_size_width',
            field=models.IntegerField(default='19', max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='square_footage',
            field=models.IntegerField(default='2000', max_length=20),
        ),
    ]
