# Generated by Django 4.2.4 on 2023-11-09 07:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingchallenge', '0012_alter_car_num_spots_alter_car_spot_size_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(max_length=7, unique=True),  # Modify this line
        ),
    ]
