# Generated by Django 4.2.4 on 2023-11-09 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingchallenge', '0013_alter_car_license_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(max_length=7, unique=True),  # Modify this line
        ),

    ]
